import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RoleProvider } from "./context/RoleContext";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import ClientBootstrap from "./components/ClientBootstrap";
import { AuthProvider } from "./context/AuthContext";
import Header from "./components/Header";
//import "bootstrap/dist/js/bootstrap.bundle.min.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <RoleProvider>
            <ClientBootstrap />
            <Header />
            {children}
          </RoleProvider>

        </AuthProvider>

      </body>
    </html>
  );
}

