# This workflow will build and deploy your static site from wwwroot to Azure Static Web Apps
# Place this file at .github/workflows/azure-static-web-apps.yml in your repo

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      # If you have a build step, add it here (e.g., npm install/build)
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Upload wwwroot to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: 'upload'
          app_location: 'wwwroot'
          output_location: ''
