# This workflow builds and deploys the React SPA frontend to Azure Static Web Apps
# The ASP.NET Core WebAPI is deployed separately to Azure App Service via quick-deploy.ps1
# Place this file at .github/workflows/azure-static-web-apps.yml in your repo




name: Azure Static Web Apps CI/CD




on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master




jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4




      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
         
      - name: Build SPA
        run: |
          echo "Building SPA from frontend/spa"
          cd Frontend/spa
          npm install
          npm run build




      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: 'upload'
          app_location: 'Frontend/spa'
          api_location: '' # No API - using separate App Service for WebAPI
          output_location: 'dist'