# This workflow will build and deploy your static site from wwwroot to Azure Static Web Apps
# Place this file at .github/workflows/azure-static-web-apps.yml in your repo

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Debug - List repository structure
        run: |
          echo "=== Repository root contents ==="
          ls -la
          echo "=== Frontend directory contents (if exists) ==="
          ls -la frontend/ || echo "frontend directory not found"
          echo "=== Looking for spa directory ==="
          find . -name "spa" -type d || echo "No spa directories found"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build SPA
        run: |
          if [ -d "frontend/spa" ]; then
            echo "Building SPA from frontend/spa"
            cd frontend/spa
            npm install
            npm run build
          else
            echo "ERROR: frontend/spa directory not found!"
            echo "Available directories:"
            find . -maxdepth 2 -type d -name "*spa*" || echo "No spa directories found"
            exit 1
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: 'upload'
          app_location: 'frontend/spa'
          api_location: 'AzureFunctions/TKDHubFunctions'
          output_location: 'dist'
